Diagnostics:
  ClangTidy:
    Add: 
      - modernize*
      - clang-analyzer-*
      - llvm-*
      - google-*
      - readability-*
      # - readability-else-after-return
      # - readability-static-accessed-through-instance
      # - readability-avoid-const-params-in-decls
      - cppcoreguidelines-*
      # - cppcoreguidelines-non-private-member-variables-in-classes
      - misc-non-private-member-variables-in-classes
      - misc-unused-parameters
    Remove:
      # magic numbers
      - cppcoreguidelines-avoid-magic-numbers
      - readability-magic-numbers
      - modernize-use-trailing-return-type
      - google-build-using-namespace # to use `using namespace std` in competitive programming
      - cppcoreguidelines-macro-usage # to use dirty macro in competitive programming
